### ISSUE TITLE
添加基金净值爬取

### ISSUE THREAD

**Issue by tyehuoPHD** [Jerry1014/FundCrawler#13]
基金净值数据是基金的一个重要方面，有待爬取，如有可能，望加上这个feature。谢谢！

**Comment by Jerry1014** [comment]
有人提过了，下次重构加。

**Comment by noword** [comment]
下次是啥时候？
翘首以盼中

**Comment by Jerry1014** [comment]
最近任务有点多啊，实在是抽不出时间来。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jerry1014/FundCrawler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 上午9:25
收件人:&nbsp;"Jerry1014/FundCrawler"<FundCrawler@noreply.github.com&gt;;
抄送:&nbsp;"黄相铭"<xiangming.huang@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Jerry1014/FundCrawler] 添加基金净值爬取 (#13)





 
下次是啥时候？
 翘首以盼中

**Comment by yuanyiwei** [comment]
还会有吗（

**Comment by Jerry1014** [comment]
> 还会有吗（

已经加上了呀

**Comment by yuanyiwei** [comment]
我是指某只基金的所有交易日的单位净值数据/历史净值（？
似乎 `data_mining_type` 里没有这样的
