### ISSUE TITLE
基金爬取不完全

### ISSUE THREAD

**Issue by wyxplus** [Jerry1014/FundCrawler#18]
您好，我有个问题下请教下，请问下您爬取的地址为什么要选这个网址？

> page = requests.get('http://fund.eastmoney.com/Data/Fund_JJJZ_Data.aspx?t=1&lx=1&letter=&gsid=&text=&sort=zdf,'
                            'desc&page=1,&feature=|&dt=1536654761529&atfc=&onlySale=0', headers=header)

例如编号为159928这支场内基金没爬取到。
我查询到下面这个网址可以爬取全部的基金信息。
> http://fund.eastmoney.com/js/fundcode_search.js

**Comment by Jerry1014** [comment]
这个是当时找的搜索接口。
感谢提醒，下次我调研然后替换一下。
