### ISSUE TITLE
天天基金网基金类型有改变可能导致程序无法正确解析类型和收益

### ISSUE THREAD

**Issue by lujiaxuan0520** [Jerry1014/FundCrawler#23]
目前执行会提示“出现无解析方法的基金种类”和“出现无法解析收益的基金”，怀疑是天天基金网的基金类型和程序里的不再对应

**Comment by lujiaxuan0520** [comment]
Parser.py第34行改成
fund_kind_belong_to_index = ['股票型', '混合型-偏股', '混合型-灵活', '混合型-平衡', '混合型-偏债', '指数型-股票','债券型-长债',
                                 '债券型-混合债', '债券型-可转债', '债券型-中短债', 'QDII', '商品（不含QDII）']
或许就行

**Comment by Jerry1014** [comment]
感谢反馈，过一段时间再修吧，最近抽不出来

**Comment by jalenye** [comment]
> Parser.py第34行改成
> fund_kind_belong_to_index = ['股票型', '混合型-偏股', '混合型-灵活', '混合型-平衡', '混合型-偏债', '指数型-股票','债券型-长债',
> '债券型-混合债', '债券型-可转债', '债券型-中短债', 'QDII', '商品（不含QDII）']
> 或许就行

我先试下你这个，兄弟如果改好了，麻烦告知。

**Comment by Jerry1014** [comment]
兄弟最近在吭呲吭呲面试呢，你改完要是好使的话，直接提pull request，我merge进主分支。
我的话，就是周末或者下周末了。

发自我的iPhone

**Comment by jalenye** [comment]
我跑了，没有报错了，感谢两位老哥，我不懂怎么pull request，就不添乱了。
此外，我跑的时候经常出现这个提示“爬取进度:[#######################  ] 95%如果此条提示持续出现，请检查当前的网络状态”应该不是大问题。
